### PR TITLE
Remove unnecessary url launcher plugin from dependencies

### PR DESCRIPTION
**Pull request by cheymos**
#86

### CODE REVIEW

**Comment by cheymos** [comment]
@zathras Hello! What do you think about this change?

**Comment by zathras** [comment]
Thanks for spotting the problem.  I'm not sure why you moved the Flutter SDK dependency down to 3.0; it was at 3.16 for a reason.  I'd have to dig through the record to remind myself what that reason was; probably related to a Flutter platform bug that was fixed,though.  Anyway, I just removed the offending dependency directly, and ran flutter upgrade in  various places myself.

**Comment by cheymos** [comment]
> Thanks for spotting the problem. I'm not sure why you moved the Flutter SDK dependency down to 3.0; it was at 3.16 for a reason. I'd have to dig through the record to remind myself what that reason was; probably related to a Flutter platform bug that was fixed,though. Anyway, I just removed the offending dependency directly, and ran flutter upgrade in various places myself.

Thanks!

**Comment by cheymos** [comment]
> Thanks for spotting the problem. I'm not sure why you moved the Flutter SDK dependency down to 3.0; it was at 3.16 for a reason. I'd have to dig through the record to remind myself what that reason was; probably related to a Flutter platform bug that was fixed,though. Anyway, I just removed the offending dependency directly, and ran flutter upgrade in various places myself.

I didn't notice why Flutter SDK dependency is down to 3.0. I just removed the dependency using `flutter pub remove`. And for some reason the Flutter SDK dependency has changed.

**Pull request closed without merging**
