### PR TITLE
Add rgba support.

### PR DESCRIPTION
**Pull request by xuelongqy**

### CODE REVIEW

**Comment by xuelongqy** [comment]
Svg: https://openseauserdata.com/files/ebc71d24dd7fa79fdd3b44076ccddb44.svg

**Comment by xuelongqy** [comment]
SVG is driving me nuts 😂. I have little exposure to svg parsing before, so I'm not sure if this is the right way to do it.

**Comment by zathras** [comment]
I updated the README to mention `transform-origin` not being supported.  It looks like CSS's transforms are pretty different than SVG's, and substantially more complicated.  Supporting CSS transforms would be a substantial step toward full CSS support, which would be a substantial endeavor.

**Comment by xuelongqy** [comment]
1.1.9-rc.2 works fine in my project. But there is a problem. I can clearly feel the stuttering, especially when the list is scrolling. I wonder if it is caused by too many elements. My current approach is to use jovial_svg to convert svg to image display, and use ScalableImageWidget + PhotoView for preview, but I can feel obvious lag when zooming. I know the test conditions are harsh, but maybe there is room for optimization.

I've tried adding support for **transform-origin**, but I haven't found a suitable way, I'll do some more research in my spare time.

Svg Resource: https://opensea.io/collection/slashes

https://user-images.githubusercontent.com/27658205/212221570-ca20c669-b5b6-412d-91bd-e6b253730ef9.mp4

**Comment by zathras** [comment]
Well, about `transform-origin`...  What's your real goal here?  Are you trying to make it so that you can view any valid SVG file?  Because that's a very big goal, and well outside the scope of jovial_svg.  SVG 2.0, all of CSS, and all the other stuff that browsers implement as part of rendering SVGs is HUGE.  If you got CSS's `transform-origin` to work, then you'd probably just run into other stuff, in an endless cycle of discovering more and more of the SVG specification.

How are you creating these images?  Can you just make your authoring system not use the more esoteric CSS features?

About performance:  You mean the performance when zooming into one image, after you've selected it, right?  Most likely, it's GPU-bound.  A complex SVG file translates into a large number of drawing operations.  Effectively zooming around a complex scene is a pretty demanding thing to do.  The normal technique is to pre-render it into a pixmap, then zoom around that.  At a suitable time, you re-render at the current zoom.

You can see that this is what's done by applications like Google Maps.  When you quickly zoom it, everything is pixellated; after a while, the app decides to re-render with the current zoom, and the resolution picks up.

You could certainly use jovial_svg to render to a pixmap, but coordinating all of this for the best user experience would take some work.  You'd probably want to do the rendering in a separate task, too.

**Comment by xuelongqy** [comment]
Well, hearing you say that, I realize that `transform-origin` is really not an easy thing to do.

I use jovial_svg to convert SVG to ImageProvider, which can avoid redrawing of svg in scenes that do not require preview. I made this function into a Flutter package [flutter_svg_image](https://pub.dev/packages/flutter_svg_image). Thank you very much for your methods, I think they can be combined to optimize the svg preview.

In my project, the requirements for SVG are not high. After all, currently in the mobile app, there is no way to fully support SVG except for WebView.

**Comment by zathras** [comment]
It's great to see your `ImageProvider` - cool!

For scrolling, the bottleneck might be parsing the SVG.  Parsing XML is expensive.  If you control the backend, you could always compile the SVG files to SI, which is about 10x faster to parse.

To expand on optimizing zooming -- I'm guessing it's spending all its time in the paint() call, constantly re-rendering.  If I were trying to speed up that, I'd first run with profiling, to make sure that that is really what's happening!

Assuming it is, I'd first try just wrapping the widget being zoomed in a `RepaintBoundary`.  I don't _think_ `RepaintBoundary` protects its child against constant re-rendering when the scale changes by just a little bit, but maybe it does?  And, maybe `RepaintBoundary` helps when scrolling?  

Assuming it doesn't help with pinch/zoom, it would be an interesting project to make a caching widget a little like `RepaintBoundary`, but one that tries to rasterize its child in a way that works well for zooming and panning.  Maybe it could have one raster of the whole image, but then when zoom/pan settles on an area of an image, make a higher-resolution raster of just that part?  It would take some experimentation to come up with a pleasing algorithm, I bet.

I did something a little like this about a year ago, when I was playing around with making a card game.  No pinch/zoom, but I found that animating cards moving around the screen was too slow on an old tablet computer I have.  In that application, there were just 52 cards, so fully rasterizing all of them at the device aspect ratio was straightforward enough -- I paid maybe a second or two of startup time on that slow hardware, but got much faster animation in return.

That code is totally undocumented, since I was really just playing around, but the program is at https://aisleriot.jovial.com/ (click on the image to run the web version), and the thing that does the rasterization is _CachingCardPainter at https://github.com/zathras/aisleriot/blob/main/lib/graphics.dart

Making an optimizing rasterizer for pinch/zoom and scrolling would be a much more ambitious project, of course!  I bet other people have this problem with wanting to do pinch/zoom of things that are expensive to render (and not just with SVGs).  So maybe someone's already done this somewhere?  Or if not, maybe it's something the community would find useful?

Maybe for scrolling, it could make sense to have pre-rendered thumbnails (as PNG images) on the backend, and then switch to local rendering of the SVG when one is selected, and presented at higher resolution?

Anyway, just some random thoughts.  I'll publish 1.1.9 with rgba and the other fixes soon.

**Comment by xuelongqy** [comment]
Thank you very much. Real-time rendering really affects performance a lot, I will optimize the project according to the method you provide.

**Pull request merged**
